import { StoreLayout } from "@/components/store-layout";
import { Locale, i18n } from "@/lib/i18n";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ locale }));
}

export default function RootLayout({
  params,
  children,
}: {
  params: { locale: Locale };
  children: React.ReactNode;
}) {
  return (
    <html lang={params.locale}>
      <body className={inter.className}>
        <StoreLayout locale={params.locale}>{children}</StoreLayout>
      </body>
    </html>
  );
}
